apiVersion: apps/v1
kind: Deployment
metadata:
  name: subnet-router
  namespace: tailscale
  labels:
    app: tailscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale
  template:
    metadata:
      labels:
        app: tailscale
    spec:
      containers:
      - env:
        - name: KUBE_SECRET
          value: tailscale-auth
        - name: USERSPACE
          value: "true"
        - name: AUTH_KEY
          valueFrom:
            secretKeyRef:
              key: AUTH_KEY
              name: tailscale-auth
              optional: true
        - name: ROUTES
          value: 10.0.0.0/20,10.124.0.0/14
        image: kingdonb/tailscale-k8s:0.0.8-gke
        imagePullPolicy: Always
        name: tailscale
        securityContext:
          runAsGroup: 1000
          runAsUser: 1000
      serviceAccountName: tailscale
