apiVersion: v1
kind: Pod
metadata:
  labels:
    app: tailscale
  name: subnet-router
  namespace: tailscale
spec:
  containers:
  - env:
    - name: KUBE_SECRET
      value: tailscale-auth
    - name: USERSPACE
      value: "true"
    - name: AUTH_KEY
      valueFrom:
        secretKeyRef:
          key: AUTH_KEY
          name: tailscale-auth
          optional: true
    - name: ROUTES
      value: 10.96.0.0/12,10.244.0.0/24,10.17.12.0/24
    image: kingdonb/tailscale-k8s:0.0.3
    imagePullPolicy: Always
    name: tailscale
    securityContext:
      runAsGroup: 1000
      runAsUser: 1000
  serviceAccountName: tailscale
