---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: scrob-demo
  namespace: default
spec:
  interval: 7m44s
  timeout: 2m0s
  retryInterval: 30s
  path: ./demo
  targetNamespace: default
  prune: true
  sourceRef:
    kind: GitRepository
    name: scrob-web
    namespace: scrob-dev
