---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flux
  namespace: flux
spec:
  chart:
    spec:
      chart: flux
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: fluxcd
        namespace: flux-system
      version: '*'
  interval: 10m0s
  timeout: 1m0s
