---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: tf-controller
  namespace: tf-controller
spec:
  interval: 1m0s
  url: https://weaveworks.github.io/tf-controller/

