apiVersion: v1
data:
    token: ENC[AES256_GCM,data:lVj0t96EB3IzHaZFEuS9Q9WWO7PeATf0QnWJtCgZ1LOVzlUkZk5f/xA9RRM=,iv:acd/zUtuhUa7KXMIxXRYkaVVWTbKf9mKruqhm6Tzaxg=,tag:gY2dHXNlXpGK9nuVzus1Ng==,type:str]
kind: Secret
metadata:
    name: webhook-token
    namespace: podinfo-flux-oci
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-09T20:16:08Z"
    mac: ENC[AES256_GCM,data:x0zDfoQDK3wEAa26Z79wvxLfmnN6Sa2gGMgxMsb3ZkNB+CUGn9zGkcHEJACkv9A+p35HvloZjr3Kygd/GORSnJScAXD1UUipqtI76A1cVbjHDxfSxyu7YTceaZr9UYnkXe0WpgcOOXhFWU9PBfk72WrXBDWkuf2hvwXHpiyXJeA=,iv://fiqVHLOs0f4CdDUmK9nI1bjL16ZcKh6IFszMuXXYc=,tag:86IZhhJKBG0TAcjunYWYqQ==,type:str]
    pgp:
        - created_at: "2022-08-09T20:15:38Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2nxU4+VO/O6ARAAs8peT3QEaiGRdPQWbkJKhqwImmFEpm9sCvMJ++4kYDCT
            eupYN3z9jvayjg23P4Fys0VNisFrreD4Q4i+frWvF40/uDPOctlqIQ+/5cxuXfru
            3TTq/2lEVGlirAfJiBUjrof46T55HVPgDOxi7/+3H8MEuEGU104tgE0lF246zwhv
            rMPlEkyfcMtwfa+qXz6JrnVILKEMijrUgqIIj00M62nt6IEIvguYILSTcmduVL7C
            WaTnPm/98mI3Q5kTO5aTv7wymoS56AGFOD4YO2OWAOS5mIfSJv/01CAIDtBDTvGt
            71UzOryqoiYJTQwCO3380vYQ7rruEVuHH5ZU+ik6FItskkBWZTh+e5CrULcRXW0c
            x+1h0c9fDP+zZL71JkC0bRP8JmYobt0Jmxubc9Da8pZNShVjHVVcGOC9GaMQ6mV6
            2F5tkY+IvaD6/0D18ouJnF8cKbkRzxl82rrBTFk+uUwQlb/+girrGG1zSRzg6LSe
            ovaKy5WEJhptN/v14vFNGd0PSqAIL7mhGQFbJXFnKpShAasNM8efVVjzBDTrO7aG
            BLLDqG32NKMD57fIqy6PSJOlHXncec0ge+mizAlHr0LJS75ybHlG0LaOiOYFWYmr
            xr5TZ73nwJKSn3Qk7TPNieWyOp9TxYcOaAYup5Jy1sl7LPLpJlJpjfRJZ2uXVGnU
            aAEJAhDxL7SsRNv/n3wRKxF+sc6PG+wRdHgUm5mKwXjU0J7+Yatu+5DzXphC7Qes
            bBopvlyt4yRSR7ZMxX0rpwdiJLxxbqpm6PwZJ5itbQtWD0RVi9okLzXzOOSEYW9K
            fOcj74tYncJO
            =XwlA
            -----END PGP MESSAGE-----
          fp: 77B4CAB8CCDCD8DBA896024D565E8274AAA8A369
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
