---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: river-data-stg
  namespace: river-data
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: yebyen+fluxcd@gmail.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: main
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system-rw
  update:
    path: ./apps/worker/river-data-explorer
    strategy: Setters
