---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: example
  namespace: river-data
spec:
  imageRepositoryRef:
    name: river-data-example
  filterTags:
    pattern: '^.*-[a-fA-F0-9]+-(?P<ts>.*)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
