---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: river-data-ro
  namespace: flux-system
spec:
  gitImplementation: go-git
  interval: 1m0s
  ref:
    branch: deploy
  timeout: 20s
  url: https://github.com/kingdonb/river-data-explorer.git
