# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
#
# namespace: default
#
# resources:
# - resources.yaml
# - job.yaml
#
# replacements:
# - path: my-replacement.yaml
# - source:
#     kind: Secret
#     name: my-secret
#   targets:
#   - select:
#       name: hello
#       kind: Job
#     fieldPaths:
#     - spec.template.spec.containers.[name=hello].env.[name=SECRET_TOKEN].value
