apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Receiver
metadata:
  name: podinfo-package
  namespace: podinfo-flux-oci
spec:
  events:
  - package
  - ping
  resources:
  - kind: OciRepository
    name: podinfo
    namespace: podinfo-flux-oci
  secretRef:
    name: webhook-token
  type: github
