apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo-oci-production
  namespace: podinfo
spec:
  interval: 10m
  targetNamespace: podinfo-flux-oci
  sourceRef:
    kind: OCIRepository
    name: podinfo
    namespace: podinfo-flux-oci
  path: ./deploy/overlays/production
  wait: true
  prune: true
