apiVersion: v1
kind: Secret
metadata:
    name: flux-system-rw
    namespace: demo
stringData:
    identity: ENC[AES256_GCM,data:zwxe41GkqF5eiM71wy6jlpjbq3gGAlP3RXtcoQhDzlRK58lkqoZ94tT7fceyOuz9IomBg5wWgNo3A5O8e6vlejh2/UCsH/Dp55xsAPEwIUaGwYiErk8srh4wIHCBauo85Ozct+wmAew3yGaqb7Il/7lwvWjHCdhwR7raXAcHBrj+iyI/xQyOCeUTgcFhezXrgvQ++I1EQTwViOBkyFAEiugNY4uio5Ea+2GDl97L4dUyK5igRQAu5GBCl7K9T13CxQTkl+PO3OVrK1tWrBzgpPvsbwKuJeN8aDEOokl6JdOSZDpWgq7BaUi+qplkZh9LhDYOi50Gnml3LuTLG2BsWdv9phXFbH6Wn8xgcSEfyUMSXB7M9oFpP45m0d05WU374bGUq3YiaRZPBlSuNJ4mlCO1,iv:e02kmsKQ8/yoilLxVA0YLYGd+L7kAxTLJ0+A5ziCkzY=,tag:clXbAoU/4t82KxwhjC7LWA==,type:str]
    identity.pub: ENC[AES256_GCM,data:yGl1HjFSvr2nD2IjvRHz+ejOBnojWKHZdVr5XnVNz6B6xSGibG8T2VwAUJNuocjgvvxxln0zLBPcvz7iAPAUbHHyhKX3oO945I8wa/5jjultR9P0KnmyVpd8A0ZRZOiU0ZcartNHfCwS5RrQaCtUkuicRnpYLz2Z3fzqHjScOJ7oIhOwuG746KK8FZ7hxYqzCb08T8p7oRGaeMiqX9jAavBZb8WtCtOUE79qXNbhhFhzLAwPzva8FHA/Wnei6E4rZtmGTlspogLI1dqnpA==,iv:5sEgC/s7VIlQ4qlQghzx9XeitEeeNOoeE3+si1PgTLs=,tag:puij+Hm/IOqK/GvS3/UILg==,type:str]
    known_hosts: ENC[AES256_GCM,data:j/W1ZloDg8Q6DZ2Ronjgar8ebU7fRCfXLsPTwWyZ4wNVZANWdE1w0CipJFa5wdchq/F3yoxOoiEFR+SywTKJ09RHrtWyNhieFFUofbzSDCUOIuJsTambdpyIjGHQ6ttH3jeMkJnptdFj8wtLF5nJSEkRSye/Wb6ZbMMykq09OFx52X/eZSnv/bMXHzYBblfHap0CH3WsgwPVwOMoqkL1PmXmtwLEBw8biaRw,iv:6+gMA98ZO2zOW1eeqVFupDQy1KpGZ4wZLtgfM+6V9Kk=,tag:f2TYhJiRmutrY+qz3b2IiA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-01T01:06:49Z"
    mac: ENC[AES256_GCM,data:4icoVgZVWWHMCv3jmzo/pIEV5u+/DFxsCx5NuGLiXH1IzjHErYkmhLxYgOFMEuKaF0OHIEP6SUeb+JHMZpbdrT5F1aVBPhwlKVg5MB6xu6O0oz5l/XzvvGvGzn/ZyuEOF+9589Ml05KU8XnS83MAZCy+YLuHVqsG7mU6owhfJO8=,iv:lYGwroxz2ZIMzGCNe79/m0TKJmZ02pLKSifYIskWUMg=,tag:TWo0xg2VUolvNoTX0E+qLQ==,type:str]
    pgp:
        - created_at: "2022-06-27T23:29:50Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0t8tQZCaziPAQ/+NgIKILTSTsMT7JTrueBkJh/XqUZTE+LFlqV8xUT3ZLx5
            mBrH+lBafXUqXRwikWJawlgN5hQYmzL2RdAvRu5nCl4mN7J/KyDozvpkvYHFrSDB
            vIlppffwVigz1j5OOhnyqHdhcaQfAiTszNjLpBsqHDQpu7C646cimSYXyFU+d9Ml
            inSiMcDE+t9za5foIJQRc8kBGrzdoM30QsgCmKBm4oR45yR2G3IiYnYNoEnKhcW5
            XXzbWZqBXV3zNKlQuwe1QdNb+zmr/BYPx3y0aGzKFk2oHoAJL91IQ7VG4R2zR5BF
            YVYDW1WZ+bIIZVxcZJcR0aZkaD74IoTujB14hnuS+kLQcUwWqq6Nu6pD+WlZdtIK
            aYXM3IJ+JgQ+jt0r3KhCGI7Wo6HB8GEu+JtAgpfXYym1uzB8qaXm3Yr+RSZp+GnE
            T6l6jTW3g7wBJxHqd4sndP70AfEU/ZZg/okvYH2pc1ap6PDF3REMhUQ19VZoGwvm
            cd3RILqMKgOx+Z3C1XJkSxuieEuh7wBD69nsKFLybMw6EtNTmwaWT1LM1Em1iJfh
            yMknFiRbVGWV9nBUUU4HxN0/gjNtSn9uUnmjwEisBcJmNrnxeo3MrBrXVDaOKNK8
            W5J4VbaajCAVvsn/PtwWgyNKx1NlX8anwtKQSI6oA/X8K/eJjyn6BSoTT2sTp/LU
            ZgEJAhDwTbrrPDlgl/6A35uK3Ghwbhp3NW88tu2EvXTBJ3e5fvQZrSGmXeynsMbr
            T4YpJAfnpaGG9AzuqIYnPC/rw5u63v1f6AoZSF29iDT1kUvoseBEWQzvDFXPRrrF
            FTca0hv/iw==
            =UeBo
            -----END PGP MESSAGE-----
          fp: 17BFA97BD06B9C7E14ADEDEBDC1A3B0FD2E46432
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
