apiVersion: v1
data:
    master-key: ENC[AES256_GCM,data:dQVj7AfWN6Q7QEFZGzp+slIWh1g5Ytz7k1voX0hw6y9pl4hqGaZVrkPk9s0=,iv:RpbS+yPOZM0F46PyF5x7iyZl8sQ3Uv0EG9u6R+sabI8=,tag:3SY/+fsOuvCfFm6TQAHD1w==,type:str]
kind: Secret
metadata:
    name: rails-master-key
    namespace: demo
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-01T01:06:56Z"
    mac: ENC[AES256_GCM,data:o3qHXeEeFV2Ghz3Nz1PV5+0ZP7wvJRrcZsEewFB1FOIOZNBU3UWiC8tNGLi2NxcWpg28/1VfA9r+TL/PlKwPx2zq9fOO29lhbeSwXFISNBVYWJa8Iu+KAMm3toCgrV1xt0MFSX8hiLMlGRjrKK/iQrfhwFQZ8xrny3JoXWr7Jhc=,iv:aCke6G/LV1gx6WaIuwV3nI5uaB0xKxQE1GW7cDqu3CE=,tag:q3+ag2IkLKVTqgclRZlNTQ==,type:str]
    pgp:
        - created_at: "2022-06-28T13:01:00Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0t8tQZCaziPARAArAwca66Sb3i1BImOGCmoPwag4cMZDta5GCkD8PoLRED9
            +xTjcwqKoiMK0XUcmnZOUh3MuI7UwrIueUG38Qr7L0QUqDec3UNKFCxzBYTZ0Nuf
            b7zPOt48jEGrnwnLfACrA5+zZs9frC2Hit64iRxP7mKGGcZ3HVaxQ3pOKVWv8EiE
            jCaoJuioKEu+BOXDR79Ej59rx62NKEk7KXj9ndkc3Skk4WX7s3+v1MHa7cCtY/Sy
            36WC5MR0e5GqoWBL2web68QznuAVMneH9CynPqN2CV2kFgWbO/7/0cDWy/Giva/5
            9mYi+5lUdkW2Lrejz8X6O0iYvNVRAMAglQthkqKU5+6rAHM+miYN7mSbmyeVMVol
            SxZgJAYtIOr77qsiatoJ4SnVuz+JZTtPRoR7z+2yBb6u+XzXd79hujH3esmlGLs3
            UDU+VSkz/tda8h2wCz+NqDe2pz8ca834nBgHflKz/FmQxPTJT2+RRK93CN+B9Xz6
            l606pc4e+PD2NoLEYznjfi+Tsi/cOi2RDF88ZTPDSSM1huEeTwzTJHFupj3Kikkt
            7jh3kXwt6AVH0fD2jxd8IgNAw9+M1wRZ1xB+O0+SdHR3+hHc7aXPTEIUzxMt+/fd
            mvNmAVAFN60khif2LSdRWDVSrzZwhZrgo7rRovupAC6JlnvcceCWGNk9gpNCanPU
            aAEJAhAUz0AaRZlKYTmLkyIjYyrB7FcLge/65nZJz1mEJvOJQOdPbaFGjuGWxgLJ
            OPCA49yeWO7HfJ9Axfd41McmgO2r5ZUHucAucrl3rz3bUKMMPiyYwxr/LB7bffaG
            1GUZkmBUgY6A
            =HbM7
            -----END PGP MESSAGE-----
          fp: 17BFA97BD06B9C7E14ADEDEBDC1A3B0FD2E46432
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
