---
apiVersion: v1
kind: Namespace
metadata:
  name: podinfo-helm-oci
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: podinfo
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 10s
  ref:
    branch: master
  url: https://github.com/kingdonb/podinfo
