---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: scrob-demo
  namespace: default
spec:
  interval: 7m44s
  timeout: 2m0s
  retryInterval: 30s
  path: ./demo
  targetNamespace: default
  prune: true
  sourceRef:
    kind: GitRepository
    name: scrob-web
    namespace: scrob-dev
  patches:
    - patch: |-
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: scrob
          namespace: default
        spec:
          template:
            spec:
              containers:
              - image: ghcr.io/kingdonb/scrob-web:c2c8947
                name: scrob
