---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo-auto
  namespace: podinfo
spec:
  interval: 1m0s
  path: ./kustomize
  prune: false
  sourceRef:
    kind: GitRepository
    name: podinfo
    namespace: flux-system
