resources:
# - gitrepo.yaml
# - flux-kustomization.yaml
#- deploy/overlays/automate
# - podinfo-ns.yaml
# flux-oci demo stuff:
# - flux-helm-demo.yaml
# - flux-oci-demo.yaml
# - flux-oci-ns.yaml
# - helm-oci-ns.yaml
