resources:
# - flux-oci/
# - helm-oci/
- podinfo-ns.yaml

# Uncomment me if shutting down flux-oci experiment above
- podinfo-flux-oci-ns.yaml

# More complicated version:
#- flux-oci-demo.yaml
#- flux-helm-demo.yaml
#
# Why use a more complicated version?
# - For Flux to enforce RBAC, different namespaces and service accounts must be used
# - You can set `targetNamespace` in a Flux Kustomization, fencing off tenant config
# - Compartmentalizing: when it fails, don't cause the whole synchronization to stop
