---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  chart:
    spec:
      chart: vault
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: hashi
  interval: 15m0s
  timeout: 2m30s
  releaseName: vault
  values:
    server:
      ha:
        enabled: true
        replicas: 5
