apiVersion: v1
data:
    slack-api-url: ENC[AES256_GCM,data:C1O5GAVUE26D+C6NcOyY+9WKHRLkf37ppL5tFEI3FvHRcu15sUFmBTKu+Zas8lCNC98psFh1753ntM8swB8rB1KMFitmJkKBimKaRyJx7CkNaOWX2pvlPlEu2Pcui5Z74VPvNeCHcOk0LAfY,iv:h6hZdJRWCPmm3Gv2Y3s5dptNe93hJajjS2xcV5h3SC4=,tag:0kdzWBIS+xOwqUY2wErLnw==,type:str]
kind: Secret
metadata:
    name: slack-api-url
    namespace: monitoring
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-06-02T18:22:42Z"
    mac: ENC[AES256_GCM,data:LgsCjw25APv4IOgkeOY8fJYSQDCm+H4I1vHPm+FZLaWhzNVmnAQDxGu2ysk4F2BsXNCGey6TeUqJY2T7Bv5jBbwGjfBJURyhCmkpExzBLm7MmmpzTFw5v2UcwqiPCjTCqAp3seVPjuStJgzzGSZ5p4uSx6Qogh15/sZhjvvsMKo=,iv:QHlddWePmxhoBuAmhif/rs+1FiCWHfrlBm9gECAQ6fc=,tag:onHpuR/8FwyianMzZTazgw==,type:str]
    pgp:
        - created_at: "2022-06-02T18:22:41Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2Qt5rLazHQGARAAnkTwIpGhuVKS7UZf3JVx1BhM/Yuqx8sihLhXWM8rxZJV
            DOxInXr16vOV6rh5bZfXn+IMjAW4G0YzA+25W48IXDplFIcOMrsusMGYRmsFjW26
            U6fdL+qyKFA0GYoXCuoxKFdcBcYJSf6e2xg+CyrY4WLIrBaUmi7dQyg1nCC2ftBu
            VyJ3DajQd7P6si4Cd1HUmBgNwBYPmaTbHY1P9g8pgf/d0udW+01sz2E8K4Z2ijau
            CjGSKrrCav/ZTYbIK3fS4Z95aYnFXyqrLzRLnrPfzfQN8m6omQsl9aF05vcph6lO
            qwLxgPhZXQPvsS6H+zUgon9FnuEmJE6XKZSooZFVQfNNEjvM8WoCvoNKfLlAkBnx
            BYtqZd7uCLfmUHwBEby3nSEOzP59hv1zC98FJpu6Z3a4duqbtzHocAVta8XZMn8+
            JUGK9Z4pqy6UifHQS2p54kvuUbnY75qjn7SP1F9sd9sNa7Yg4WKy9WZDxyyi6N4/
            oq6z65tST5wvHO7rBJwLiRM2FsKO7s3C4tY2oFcpPobyPIO4aTrFNMM95N6IcmjK
            SqNeEG/Ns3wuj6Z98lVrIVua8y6SMGv0zOTBYh/PMPdQ9f149dFhpncOMZmrfjIp
            Coj+yDPQkP6JQxw12GjPzIAzQ9hJVHhb+a8a28AX9bUakseNa8bcouUqPSS/Q4rU
            aAEJAhBPalFaHFWFuY6WYDb5QG1xaGX7XBbOqaECqwf1uKVx4ELTrLMoqmpg9lTG
            lyP1Qwgqh++mTfuywbYXO/FjU9VyqcUn3EOXuxcajfXxcBCsVDUUmNYNsgUoIBif
            TfsBY7FxJlP7
            =xFhh
            -----END PGP MESSAGE-----
          fp: 1FC5A3E82B5951897BB79BF8B746C5D7D7029CCE
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
