---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flux
  namespace: flux
spec:
  suspend: false
  chart:
    spec:
      chart: flux
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: fluxcd
        namespace: flux-system
      version: '*'
  interval: 10m0s
  timeout: 1m0s
  values:
    image:
      tag: 1.25.2
    git:
      url: git@github.com:kingdonb/tailscale-k8s.git
      branch: main
      path: ./legacy
    dnsConfig:
      options:
        - name: ndots
          value: "1"
    registry:
      excludeImage: cr.l5d.io/linkerd/*,docker.l5d.io/buoyantio/*,ghcr.io/fluxcd/*,ghcr.io/linuxserver/*,index.docker.io/kingdonb/*,index.docker.io/jenkins/*,index.docker.io/library/*,index.docker.io/okteto/*,index.docker.io/weaveworks/*,index.docker.io/grafana/*,index.docker.io/datawire/*,index.docker.io/hephy/*,index.docker.io/fluxcd/*,index.docker.io/prom/*,index.docker.io/buoyantio/*,index.docker.io/kiwigrid/*,index.docker.io/rancher/*,k8s.gcr.io/metrics-server/*,k8s.gcr.io/ingress-nginx/*,k8s.gcr.io/kube-state-metrics/*,k8s.gcr.io/coredns/*,k8s.gcr.io/kube-proxy,quay.io/keycloak/*,quay.io/jetstack/*,quay.io/metallb/*,quay.io/kiwigrid/*,quay.io/prometheus/*,quay.io/prometheus-operator/*,127.0.0.1:5555/*,index.docker.io/kindest/*
