---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helm-operator
  namespace: flux
spec:
  chart:
    spec:
      chart: helm-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: fluxcd
        namespace: flux-system
      version: '*'
  interval: 10m0s
  timeout: 1m0s
  values:
    git:
      ssh:
        secretName: flux-git-deploy
    helm:
      versions: v3
