---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: my-secrets
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  interval: 10m0s
  timeout: 30s
  path: ./secrets/equinix-arm64
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
