---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: monitoring
  namespace: flux-system
spec:
  gitImplementation: go-git
  interval: 30m0s
  ref:
#    branch: monitoring
    branch: main
  timeout: 1m0s
  url: https://github.com/fluxcd/flux2
