apiVersion: v1
data:
    identity: ENC[AES256_GCM,data:61dNJTRO1M+fLW7PSmJ70le++521xa4nJRakkUVEUHOLY8k4d2WQqu0RJ3dJcmX1pdU/3AfNMUONnF6TTock6Ya0qqtqkMK1KtVRTPDvOO6Ch2fPvbSXVAWlL1D3dru5hAc3hJqSb18iJQhA7F7BNaXE/BMy+8nfLhajctKAUwH/SzzbeVpRpJFTpd3a/I/ra4+uWRHG1q+FsBLkHa9szc+0+WEho2+BqQWHAIOa9Xws6ON1dm4gLd+6n5QXRzcbtmMsvPhCwyH/XQgvoTp+Aq0rxfu5Ki4DTgnx4jYxniUBMeJhOgls3djx28HXG0TPmBypbc72NmItVnOFfUB7ADScMGelbfMUGv1Hclh4mOzMNUXtB/+k8QbdLWkZwCTHuZ3dHKoI9gGRcG75zaDlKU5PzdZ8M5r+bHhMWMB0mR/+oGQBC75yJ052uvaigslSGrxl5uJC7JCG0Fygllyuan1aqPZVOo1DissnNS5d/s7Bxgl2DYzChB4bnprs0596YE6neEzrXV/qehrlPY4PkvtxNLxAgcK5,iv:D29YvC4ud1m99Tn6G2CDv4IRZjKYTjaOAmZHo7f3a2k=,tag:eMo+3b3MFnshJX4LawlQUQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:5gJ8dMdS/T62HyXSWaBzsLKQZo5YBc1DOB56PgGMm6DFGf+ibLS6i+sYV136kbpcnnERrvUvvMH5hlm3vpHoPQKXp7K74eUKBejNzzqvpogY/EY0B1tSbX18maDNCwYB3vvLSu32GEMDO8tE/+swsuOXpoYmVL7RvRYx4DtBXJljz+aOMNbZXtRD8doy8A5FqgKup13Uugk+BnReEBP8tueTGRaCgPVVBn5ln2EX/8kn8JMG+EnHqwtMGZ/U7EHAsZ70/T6vEflpYuvDyYu9zUeZiQ6x65es0E6k+7YX5umZwK0FVRS7tDSs978MoN1JUgZx4W7Fr56BuZpeKeXJErcXXQhozeyQO9OvbVaTPS40TUM/,iv:pyRMzSm6WOOF3l6ElX8YzNS4m4HSJtdSMggJyip7Ktc=,tag:FdEGpBpDwzvQL7nRqhdWKQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:iqoMD1u2F7VxTH5GU6l6kX/1ielCIHGPpO7uMHORccDJOlRvLHVOsj0s1HOg2/W6sdleTffRWTgmclXxkj1ONx9eV3Fba0k9cNwMAYZ1Mmpe3BgISKAALTSA6SQjSraymXyd6k/V2kxPXWx+7C0CGUjoL60MqwxIQ7/tDmrfIdaSvqVlR5WeaCGjV9m3oIkd70DxvtJ8jcWlKiFUhEw2tD4Nr5zwlxlKDBLX20GeWSsisMMDpc7Dn0rZ2XWhM7DSRoZ93e6vWMt3IdAGhz88eIr6qTArk74xZaBUVjFVs+A0Zg46,iv:CcqmvUOFLAKv+ucXugvEOQqpMrz8Adhzn49CHD0Hg/o=,tag:rBHEt3EHN7eIyx+4gTU2Kg==,type:str]
kind: Secret
metadata:
    name: river-data-rw
    namespace: river-dev
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-02T15:06:32Z"
    mac: ENC[AES256_GCM,data:ILYy9a0nvovepx+f9OEDbiSA6qPyyJ4Y7s193o8xutdOWWuRE6dxG41JyPufUTX3uCoWWDFaAqFoskqfsBxz5BOS/2HY4dSSy/5gAdh8fGfj8OAH/yV5t3/0skAJhw0WsPEP1+vhTAcDdyoTtMl8ZaxrhlDWK17Q3noz11+OFVo=,iv:NUaBjGqhxmSGjZpdkDDgPzKhzHstT2wZQF0t1tdUkyI=,tag:rW67Y+b//ZHQLJV38rLkHA==,type:str]
    pgp:
        - created_at: "2022-07-02T15:06:31Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyuUwnKqkkHXAQ/9FttalBGM5jSeN3+1s2h5WLEEJN0shJAfzPzfz4+tVlWz
            jpidN8TxnNsdJCdSrmGyJ7zTTvY1xjul24y4oLgrV7Kq5x7tsYcSG/H4zLWDwa2H
            clcIsdwUi9L/80KZQhsI1pUmhYwRLk9BjaS2xALBF6cuflzk8cIMsfOUgsrTOXZa
            HS7hHenjzfQP3Rb8mYs2KKD3X2T2ReuSrDCGGsibYfQ9Sd0Yw5Ro0IBSoX0V6/0j
            o6TG/JfYxEslHXitC8c5/6p8OiAe2ziYg/in0gl3sMTkMIk8AKe8VEsno2ugYp5F
            jVpOrK3lwpGrEbcSRPFjF6QWRHuRG5YamlR23qsn6JLNd891CPC8WZhQDA6ANotT
            5tI3ScVybOWZYkacD6or0XhmD58X3eN/VMpoFhmSmXynKraTukUdnb8dL8JV6s52
            k7qpcuUftjLAI37+rgZNQSbGMJZQdBHptUxuAG1/ylMqxhh+pSy4Xrxc9z66lzEG
            EjdHtIAz/SL4GkSWTHc2kT8w3XJj7SxOyjtdxVF91FDLjXhr9P3B0bjnV7r4VN7v
            WOv/JxUpFoJam32N/U8ptb9AfCejewUoOCw+CyI12BiEiqSGquAEwZSICwQLw8Cn
            XxAiKqOaUL2wpqFiFp1P4ZLbQbaHOEfGgP3ud+PXA1ueApLxc79DkqHx1ozJuTDU
            aAEJAhCz4L4dnbaa6tAi/Njxa7ffTZ9I/4fwyg0COGGLUDfVRSgY0l7SwX/7c8DT
            jIQUAdVMMIFj6Iv6KcZFitZD+SEBTZT8imfiGf1TTEvZj4yQJhiGrsdAiQjj7z6/
            F3kJyaczDGX+
            =3g0l
            -----END PGP MESSAGE-----
          fp: C10E654FD7F88088ED1EB7596AC368CCE7E04ED1
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
