apiVersion: v1
kind: Secret
metadata:
    name: tailscale-auth
    namespace: tailscale
stringData:
    AUTH_KEY: ENC[AES256_GCM,data:64Kv8LLu1BLrdk/k0cTUiMPgZV9X9lEfM8Ir+3sk4fvY020jq1nirg8=,iv:WIh8iMYpaRMhop+sSmf3TzewtEyv+9whizmyKwWCG7Y=,tag:QhklzaJju1VmV9jSiIQj2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-05-24T14:15:00Z"
    mac: ENC[AES256_GCM,data:5sBR97gbBxFEkBerMMRxN1bixJ8IL0yt8ASZ76WUfK8v2m/8mFGXawwI1NJ25q4uKy0eQbNCZVE2vrBjwnswdK0Vxh+H2bIJUSS4FOOotle6HL4iuzs1W/X8OnfyGw69uY+6hCjUe1BNH8qn13nXj53zGrhX07l/bwnJv1AlLs4=,iv:RrRCMEFmP5p/fzbJQxoKxvjbJSIkJirxYUF1CyD7JUU=,tag:QdPYwBhKnz63AyNvVrKy6g==,type:str]
    pgp:
        - created_at: "2022-05-24T14:15:00Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyuUwnKqkkHXAQ/+LDXijbjvwmbfXeIaY+QaseV1rV/TdzuS5u2TsTvnJjOf
            Nv+8wSwmVwSP3klLDBMIZydBOMM94CjsD3xatijNZ700CCCaypH1fpHog8TBmyys
            51Nrq9c3rvokFVETS7U73OM85pT3ARGxC8aOPnIOr027yB4o6/NV45MBgDZMsMSv
            lKnUyqn0NnJJanSTLA/cATXEOoyjklnKSfmMoy0Rl7lKHAJVxQsPKwOjgMP++bDx
            evAALWawaOm9nWWcbZYOKhN9p+u2glp0eTHwldA1Xi/uka8NGs4q0xdnzXPvToVb
            4JAoF4RsQsu/QXUSEcmce81J+wmmeHugVQLOULNQDQy0vyeAWFPxbC59Jr3pGw2s
            8npSLmvB5KTxGiH3woG6K3o99lcnBUl2oDuEa0v6xegPG7ec4g7q040vJWhMkMIp
            /LcxWN9/LXgxPVOrb92ypQTR5m6TUt/EXtKj2NJXYgkxoo4KV/11Efere/fjIk4q
            CLQOpfxBRUE19SqQojla4HTdXpEKAvYX7qfnB6EYckTCi08msdlhEzmz7jUkZLWa
            dujAhyGgYAhalntB6Autt7zghaSol8OKKcHLuv+KqFx677TTG8kaLK0tdr05UO9O
            PaJA7DBtNtKleYkmSsU2o6VcEyP3sCIfNE1Cv6r+/D9Rw2F67Zj38DCJNNLGxs3U
            ZgEJAhDk+COBfdOtHjcFC1o5+7j31OpM80wyyp9PeUyT2XWS5B/47NZ2nXkBXfMj
            nH5A7U8MGgOrUcOSMG7zZAvcl/uk2csH4o6A7v1pusWkiUTvYjG7WlkuX4+KKHVe
            MTeNmX5mhg==
            =jqze
            -----END PGP MESSAGE-----
          fp: C10E654FD7F88088ED1EB7596AC368CCE7E04ED1
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
