kind: Deployment
apiVersion: apps/v1
metadata:
  name: sintache
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: sintache
        image: img.hephy.pro/examples/sinatra-mustache:b1.20220628.122008 # {"$imagepolicy": "sintache:example"}
