---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  include:
    - fromPath: deploy
      repository:
        name: podinfo
      toPath: clusters/demo-cluster-1/podinfo/deploy
